# Colors (acme)

# Default colors
[colors.primary]
background =  '#ffffea'
foreground =  '#000000'

# Normal colors
[colors.normal]
black	= '#101010'
red	= '#303030'
green	= '#cccc7c'
yellow	= '#ffffca'
blue	= '#eaffff'
magenta	= '#505050'
cyan	= '#aeeeee'
white	= '#fcfcce'

# Bright colors
[colors.bright]
black	= '#101010'
red	= '#303030'
green	= '#cccc7c'
yellow	= '#ffffca'
blue	= '#eaffff'
magenta	= '#505050'
cyan	= '#aeeeee'
white	= '#fcfcce'
