[colors.primary]
background = "0x1e1c31"
foreground = "0xcbe1e7"

[colors.cursor]
text = "0xff271d"
cursor = "0xfbfcfc"

[colors.normal]
black = "0x141228"
red = "0xff5458"
green = "0x62d196"
yellow = "0xffb378"
blue = "0x65b2ff"
magenta = "0x906cff"
cyan = "0x63f2f1"
white = "0xa6b3cc"

[colors.bright]
black = "0x565575"
red = "0xff8080"
green = "0x95ffa4"
yellow = "0xffe9aa"
blue = "0x91ddff"
magenta = "0xc991e1"
cyan = "0xaaffe4"
white = "0xcbe3e7"
