# Default colors
[colors.primary]
background = '#0a0a0a'
foreground = '#18a2e2'

dim_foreground    = '#8abddb'
bright_foreground = '#18a2e2'

# Cursor colors
[colors.cursor]
text   = '#1c1c1c'
cursor = '#18a2e2'

# Normal colors
[colors.normal]
black   = '#4e4e4f'
red     = '#0492f7'
green   = '#00e9ff'
yellow  = '#04e9f9'
blue    = '#00bfff'
magenta = '#0473f9'
cyan    = '#2fe9f9'
white   = '#e0e0e0'

# Bright colors
[colors.bright]
black   = '#4e4e4f'
red     = '#055bfc'
green   = '#07fce8'
yellow  = '#00edff'
blue    = '#00a1ff'
magenta = '#0473f9'
cyan    = '#00edff'
white   = '#ffffff'

# Dim colors
[colors.dim]
black   = '#565555'
red     = '#5c93f9'
green   = '#4adbd6'
yellow  = '#63eff9'
blue    = '#88d1fc'
magenta = '#4080ce'
cyan    = '#88e1e8'
white   = '#d1d1d1'