# Colors (Cursor Light)

# Default colors
[colors.primary]
background = '#fcfcfc'
foreground = '#141414'

# Normal colors
[colors.normal]
black   = '#262626'
red     = '#cf2d56'
green   = '#1f8a65'
yellow  = '#c08532'
blue    = '#3c7cab'
magenta = '#b8448b'
cyan    = '#6f9ba6'
white   = '#ededed'

# Bright colors
[colors.bright]
black   = '#737373'
red     = '#e75e78'
green   = '#55a583'
yellow  = '#c08532'
blue    = '#206595'
magenta = '#b3003f'
cyan    = '#6f9ba6'
white   = '#fcfcfc'
