# Colors (Cursor)

# Default colors
[colors.primary]
background = '#181818'
foreground = '#e4e4e4'

# Normal colors
[colors.normal]
black   = '#141414'
red     = '#e34671'
green   = '#3fa266'
yellow  = '#f1b467'
blue    = '#81a1c1'
magenta = '#E394DC'
cyan    = '#88c0d0'
white   = '#e4e4e4'

# Bright colors
[colors.bright]
black   = '#262626'
red     = '#fc6b83'
green   = '#70b489'
yellow  = '#F8C762'
blue    = '#87C3FF'
magenta = '#AAA0FA'
cyan    = '#82D2CE'
white   = '#fcfcfc'
