# Colors (Darcula)

# Default colors
[colors.primary]
background = '#282a36'
foreground = '#f8f8f2'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ff5555'
green   = '#50fa7b'
yellow  = '#f1fa8c'
blue    = '#caa9fa'
magenta = '#ff79c6'
cyan    = '#8be9fd'
white   = '#bfbfbf'

# Bright colors
[colors.bright]
black   = '#282a35'
red     = '#ff6e67'
green   = '#5af78e'
yellow  = '#f4f99d'
blue    = '#caa9fa'
magenta = '#ff92d0'
cyan    = '#9aedfe'
white   = '#e6e6e6'
