# Colors Ef-Elea-Dark
[colors.normal]
black = '#303332'
red = '#ff656a'
green = '#7fc87f'
yellow = '#cac85f'
blue = '#57aff6'
magenta = '#f59acf'
cyan = '#6fcfd2'
white = '#eaf2ef'
[colors.bright]
black = '#5e6160'
red = '#fa7f88'
green = '#50cf89'
yellow = '#cfb27f'
blue = '#62cfef'
magenta = '#cfaaff'
cyan = '#60d5c2'
white = '#969faf'
[colors.cursor]
cursor = '#ef7fa8'
text = '#222524'
[colors.primary]
background = '#222524'
foreground = '#eaf2ef'
[colors.selection]
background = '#543040'
text = '#eaf2ef'
