[colors.primary]
background = "#fbf1c7"
foreground = "#654735"

[colors.normal]
black = "#654735"
red = "#c14a4a"
green = "#6c782e"
yellow = "#b47109"
blue = "#45707a"
magenta = "#945e80"
cyan = "#4c7a5d"
white = "#eee0b7"

[colors.bright]
black = "#654735"
red = "#c14a4a"
green = "#6c782e"
yellow = "#b47109"
blue = "#45707a"
magenta = "#945e80"
cyan = "#4c7a5d"
white = "#eee0b7"
