import = ["~/.config/alacritty/gruvbox_base.toml"]

[colors.primary]
background        = "#f9f5d7" 
foreground        = "#3c3836"
bright_foreground = "#282828"
dim_foreground    = "#7c6f64"

[colors.normal]
black   = "#fbf1c7"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#7c6f64"

[colors.bright]
black   = "#928374"
red     = "#9d0006"
green   = "#79740e"
yellow  = "#b57614"
blue    = "#076678"
magenta = "#8f3f71"
cyan    = "#427b58"
white   = "#3c3836"

[colors.dim]        # use dark mode "bright" colors
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"
