[colors.primary]
background = "0x444444"
foreground = "0xdddddd"

[colors.cursor]
text = "0xaaaaaa"
cursor = "0xffffff"

[colors.normal]
black = "0x000000"
red = "0xff0000"
green = "0x00ff00"
yellow = "0xffff00"
blue = "0x0000ff"
magenta = "0xff00ff"
cyan = "0x00ffff"
white = "0xffffff"

[colors.bright]
black = "0x000000"
red = "0xff0000"
green = "0x00ff00"
yellow = "0xffff00"
blue = "0x0000ff"
magenta = "0xff00ff"
cyan = "0x00ffff"
white = "0xffffff"
