[colors.primary]
background = "0x333333"
foreground = "0xdddddd"

[colors.cursor]
text = "0xaaaaaa"
cursor = "0xffffff"

[colors.normal]
black = "0x000000"
red = "0xbb0000"
green = "0x00bb00"
yellow = "0xbbbb00"
blue = "0x0000bb"
magenta = "0xbb00bb"
cyan = "0x00bbbb"
white = "0xbbbbbb"

[colors.bright]
black = "0x000000"
red = "0xbb0000"
green = "0x00bb00"
yellow = "0xbbbb00"
blue = "0x0000bb"
magenta = "0xbb00bb"
cyan = "0x00bbbb"
white = "0xbbbbbb"
