# Colors Modus-Operandi-Tritanopia
[colors.normal]
black = '#f2f2f2'
red = '#a60000'
green = '#006800'
yellow = '#695500'
blue = '#0031a9'
magenta = '#721045'
cyan = '#005e8b'
white = '#000000'
[colors.bright]
black = '#c4c4c4'
red = '#a0132f'
green = '#00663f'
yellow = '#77492f'
blue = '#0000b0'
magenta = '#531ab6'
cyan = '#005f5f'
white = '#595959'
[colors.cursor]
cursor = '#000000'
text = '#ffffff'
[colors.primary]
background = '#ffffff'
foreground = '#000000'
[colors.selection]
background = '#bdbdbd'
text = '#000000'
