# Rigel theme
# Source: https://github.com/Rigellute/rigel/blob/master/alacritty.toml

[colors.primary]
background = '0x002635'
foreground = '0xe6e6dc'

[colors.normal]
black = '0x00384d'
red = '0xc43061'
green = '0x7fc06e'
yellow = '0xf08e48'
blue = '0x1c8db2'
magenta = '0xc694ff'
cyan = '0x00cccc'
white = '0x77929e'

[colors.bright]
black = '0x517f8d'
red = '0xff5a67'
green = '0x9cf087'
yellow = '0xffcc1b'
blue = '0x7eb2dd'
magenta = '0xfb94ff'
cyan = '0x00ffff'
white  = '0xb7cff9'

[colors.cursor]
text = '0x002635'
cursor = '0xffcc1b'
