[colors]
[colors.primary]
background = "0x191724"
foreground = "0xe0def4"

[colors.cursor]
text = "0xe0def4"
cursor = "0x524f67"

[colors.vi_mode_cursor]
text = "0xe0def4"
cursor = "0x524f67"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "0xe0def4"
background = "0x403d52"

[colors.normal]
black = "0x26233a"
red = "0xeb6f92"
green = "0x31748f"
yellow = "0xf6c177"
blue = "0x9ccfd8"
magenta = "0xc4a7e7"
cyan = "0xebbcba"
white = "0xe0def4"

[colors.bright]
black = "0x6e6a86"
red = "0xeb6f92"
green = "0x31748f"
yellow = "0xf6c177"
blue = "0x9ccfd8"
magenta = "0xc4a7e7"
cyan = "0xebbcba"
white = "0xe0def4"

[colors.hints]
[colors.hints.start]
foreground = "#908caa"
background = "#1f1d2e"

[colors.hints.end]
foreground = "#6e6a86"
background = "#1f1d2e"
