# Colors (Selenized Light)
[colors.primary]
background = '#fbf3db'
foreground = '#53676d'

[colors.normal]
black   = '#ece3cc'
red     = '#d2212d'
green   = '#489100'
yellow  = '#ad8900'
blue    = '#0072d4'
magenta = '#ca4898'
cyan    = '#009c8f'
white   = '#909995'

[colors.bright]
black   = '#d5cdb6'
red     = '#cc1729'
green   = '#428b00'
yellow  = '#a78300'
blue    = '#006dce'
magenta = '#c44392'
cyan    = '#00978a'
white   = '#3a4d53'

