# Spacegray, from Sublime Text
# Source https://github.com/SublimeText/Spacegray

# Default colors
[colors.primary]
background = '#20242d'
foreground = '#b3b8c3'

[colors.cursor]
text = '#b3b8c3'
cursor = '#b3b8c3'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#b04b57'
green   = '#87b379'
yellow  = '#e5c179'
blue    = '#7d8fa4'
magenta = '#a47996'
cyan    = '#85a7a5'
white   = '#b3b8c3'

# Bright colors
[colors.bright]
black   = '#000000'
red     = '#b04b57'
green   = '#87b379'
yellow  = '#e5c179'
blue    = '#7d8fa4'
magenta = '#a47996'
cyan    = '#85a7a5'
white   = '#ffffff'
