# Colors (Tomorrow Night Eighties)

[colors.primary]
background = '#3b3b3b'
foreground = '#d5d5d5'

[colors.cursor]
cursor  = '#d5d5d5'
text    = '#484848'

[colors.normal]
black   = '#3b3b3b'
red     = '#f78d8c'
green   = '#a7d2a8'
yellow  = '#fca268'
blue    = '#77a9d6'
magenta = '#d6acd6'
cyan    = '#76d4d6'
white   = '#a8a8a8'

[colors.bright]
black   = '#636363'
red     = '#f78d8c'
green   = '#a7d2a8'
yellow  = '#ffd478'
blue    = '#77a9d6'
magenta = '#d6acd6'
cyan    = '#76d4d6'
white   = '#d5d5d5'
