# Colors (Tomorrow Night Blue)

[colors.primary]
background = '#003263'
foreground = '#ffffff'

[colors.cursor]
cursor  = '#ffffff'
text    = '#00539f'

[colors.normal]
black   = '#003263'
red     = '#ffafb2'
green   = '#d8f1b7'
yellow  = '#ffce9f'
blue    = '#8597c4'
magenta = '#efc9ff'
cyan    = '#a6feff'
white   = '#ffffff'

[colors.bright]
black   = '#004680'
red     = '#ffafb2'
green   = '#d8f1b7'
yellow  = '#ffefba'
blue    = '#c6e1ff'
magenta = '#efc9ff'
cyan    = '#a6feff'
white   = '#ffffff'
