# Colors (Tomorrow)

[colors.primary]
background = '#ffffff'
foreground = '#5f5f5f'

[colors.cursor]
cursor  = '#dedede'
text    = '#f1f1f1'

[colors.normal]
black   = '#5f5f5f'
red     = '#d43d35'
green   = '#829a00'
yellow  = '#f89827'
blue    = '#5286bc'
magenta = '#9c70b7'
cyan    = '#4ba7af'
white   = '#5f5f5f'

[colors.bright]
black   = '#9fa09e'
red     = '#d43d35'
green   = '#829a00'
yellow  = '#eec100'
blue    = '#5286bc'
magenta = '#9c70b7'
cyan    = '#4ba7af'
white   = '#5f5f5f'
