# Colors (Tomorrow Night Bright)

[colors.primary]
background = '#000000'
foreground = '#eeeeee'

[colors.cursor]
cursor  = '#eeeeee'
text    = '#373737'

[colors.normal]
black   = '#000000'
red     = '#df6464'
green   = '#c5d05b'
yellow  = '#ed9e56'
blue    = '#7aa6da'
magenta = '#ceaadf'
cyan    = '#7fc9bf'
white   = '#a7a7a7'

[colors.bright]
black   = '#535353'
red     = '#df6464'
green   = '#c5d05b'
yellow  = '#ecce57'
blue    = '#7aa6da'
magenta = '#ceaadf'
cyan    = '#7fc9bf'
white   = '#eeeeee'
