[colors.bright]
black = "0x6D7070"
blue = "0x1BA6FA"
cyan = "0x73FBF1"
green = "0xB8E466"
magenta = "0xA578EA"
red = "0xFF4352"
white = "0xFEFEF8"
yellow = "0xFFD750"

[colors.cursor]
cursor = "0xFF261E"
text = "0xEBEBEB"

[colors.normal]
black = "0x0d0d0d"
blue = "0x1BA6FA"
cyan = "0x21DEEF"
green = "0xA0E521"
magenta = "0x8763B8"
red = "0xFF301B"
white = "0xEBEBEB"
yellow = "0xFFC620"

[colors.primary]
background = "0x292C3E"
foreground = "0xEBEBEB"
