[colors.bright]
black = "0x41505e"
blue = "0x5ec4ff"
cyan = "0x70e1e8"
green = "0x8bd49c"
magenta = "0xe27e8d"
red = "0xd95468"
white = "0xffffff"
yellow = "0xebbf83"

[colors.cursor]
cursor = "0x008b94"
text = "0xfafafa"

[colors.normal]
black = "0x333f4a"
blue = "0x539afc"
cyan = "0x70e1e8"
green = "0x8bd49c"
magenta = "0xb62d65"
red = "0xd95468"
white = "0xb7c5d3"

[colors.primary]
background = "0x171d23"
foreground = "0xffffff"
