[colors.bright]
black = "0x1c61c2"
blue = "0x00ff00"
cyan = "0x0abdc6"
green = "0xd300c4"
magenta = "0x711c91"
red = "0xff0000"
white = "0xd7d7d5"
yellow = "0xf57800"

[colors.cursor]
cursor = "0x0abdc6"
text = "0x000b1e"

[colors.normal]
black = "0x123e7c"
blue = "0x123e7c"
cyan = "0x0abdc6"
green = "0xd300c4"
magenta = "0x711c91"
red = "0xff0000"
white = "0xd7d7d5"
yellow = "0xf57800"

[colors.primary]
background = "0x000b1e"
foreground = "0x0abdc6"
