[colors.bright]
black = "0x020221"
blue = "0x99a4bc"
cyan = "0x8bccbf"
green = "0xb1bf75"
magenta = "0xffb07b"
red = "0xff8e78"
white = "0xf8f8ff"
yellow = "0xffd392"

[colors.cursor]
cursor = "0xffe8c0"
text = "0x020221"

[colors.normal]
black = "0x000004"
blue = "0x635196"
cyan = "0x34bfa4"
green = "0x718e3f"
magenta = "0xff761a"
red = "0xff3600"
white = "0xb4b4b9"
yellow = "0xffc552"

[colors.primary]
background = "0x020221"
foreground = "0xb4b4b9"
