[colors.bright]
black = "0x10151b"
blue = "0x093748"
cyan = "0x599caa"
green = "0x081f2d"
magenta = "0x888ba5"
red = "0xd26939"
white = "0xd3ebe9"
yellow = "0x245361"

[colors.normal]
black = "0x0a0f14"
blue = "0x195465"
cyan = "0x33859d"
green = "0x26a98b"
magenta = "0x4e5165"
red = "0xc33027"
white = "0x98d1ce"
yellow = "0xedb54b"

[colors.primary]
background = "0x0a0f14"
foreground = "0x98d1ce"
