[colors.bright]
black = "0x5b5858"
blue = "0x3fc4de"
cyan = "0x6be4e6"
green = "0x3fdaa4"
magenta = "0xf075b5"
red = "0xec6a88"
white = "0xd5d8da"
yellow = "0xfbc3a7"

[colors.normal]
black = "0x16161c"
blue = "0x26bbd9"
cyan = "0x59e1e3"
green = "0x29d398"
magenta = "0xee64ac"
red = "0xe95678"
white = "0xd5d8da"
yellow = "0xfab795"

[colors.primary]
background = "0x1c1e26"
foreground = "0xe0e0e0"
