[[colors.indexed_colors]]
color = "0xffa066"
index = 16

[[colors.indexed_colors]]
color = "0xff5d62"
index = 17

[colors.bright]
black = "0xa6a69c"
blue = "0x7FB4CA"
cyan = "0x7AA89F"
green = "0x87a987"
magenta = "0x938AA9"
red = "0xE46876"
white = "0xc5c9c5"
yellow = "0xE6C384"

[colors.normal]
black = "0x0d0c0c"
blue = "0x8ba4b0"
cyan = "0x8ea4a2"
green = "0x8a9a7b"
magenta = "0xa292a3"
red = "0xc4746e"
white = "0xC8C093"
yellow = "0xc4b28a"

[colors.primary]
background = "0x181616"
foreground = "0xc5c9c5"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"
