[colors.bright]
black = "0x6f6f6f"
blue = "0xc2e3ff"
cyan = "0xc0e9f8"
green = "0xd6fcba"
magenta = "0xffc6ff"
red = "0xfe978b"
white = "0xffffff"
yellow = "0xfffed5"

[colors.cursor]
background = "0xf0f0f0"
foreground = "0x26282a"

[colors.normal]
black = "0x26282a"
blue = "0x8bbce5"
cyan = "0xa2e1f8"
green = "0xb4fb73"
magenta = "0xffb2fe"
red = "0xff8878"
white = "0xf1f1f1"
yellow = "0xfffcb7"

[colors.primary]
background = "0x26282a"
foreground = "0xf0f0f0"
