[colors.bright]
black = "0x4c4c4c"
blue = "0xb3deef"
cyan = "0x73cef4"
green = "0xc9d05c"
magenta = "0xd3b987"
red = "0xf43753"
white = "0xfeffff"
yellow = "0xffc24b"

[colors.normal]
black = "0x282828"
blue = "0xb3deef"
cyan = "0x73cef4"
green = "0xc9d05c"
magenta = "0xd3b987"
red = "0xf43753"
white = "0xeeeeee"
yellow = "0xffc24b"

[colors.primary]
background = "0x282828"
foreground = "0xeeeeee"
